---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# osmactive

<!-- badges: start -->
<!-- badges: end -->

The goal of osmactive is to provide functions, example datasets and documentation for extracting active travel infrastructure from OpenStreetMap data.

```{r, eval=FALSE, echo=FALSE}
# Setup instructions
# Create the README.Rmd with usethis:
usethis::use_readme_rmd()
# Add description:
usethis::use_description()
# Add package dependencies
usethis::use_package("osmextract")
# Create the R directory
usethis::use_r("osmactive")
usethis::use_package("geos")
usethis::use_package("sf")
usethis::use_package("dplyr")
usethis::use_package("stringr")
# Ignore README.Rmd in build ignore
usethis::use_build_ignore("README.Rmd")
usethis::use_mit_license("Robin Lovelace")

# Add pkgdown site
usethis::use_pkgdown()
# pkgdown pages
usethis::use_pkgdown_github_pages()
# Add actions
usethis::use_github_action("pkgdown")

devtools::check()
```

Install the package with:

```{r, eval=FALSE}
remotes::install_github("nptscot/osmactive")
library(osmactive)
```

```{r, include=FALSE}
devtools::load_all()
```

## Leeds example

```{r leeds}
library(dplyr)
library(tmap)
leeds = zonebuilder::zb_zone("Leeds")
leeds = leeds |>
  filter(circle_id == 1)
osm = get_travel_network("Leeds", boundary = leeds, boundary_type = "clipsrc")
cycle_network = get_cycling_network(osm)
driving_network = get_driving_network(osm)
cycle_network_with_distance = distance_to_road(cycle_network, driving_network)
cycle_network_classified = classify_cycleways(cycle_network_with_distance)
m = cycle_network_classified |>
  arrange(cycle_segregation) |>
  tm_shape() + tm_lines("cycle_segregation", lwd = 4, palette = "-Blues", popup.vars = c("name", "cycle_segregation", "distance_to_road", "maxspeed", "highway", "other_tags"))
m
```

```{r}
#| eval: false
tmap_save(m, "classify_cycleways_leeds.html")
browseURL("classify_cycleways_leeds.html")
```

## Edinburgh example


```{r edinburgh}
edinburgh = zonebuilder::zb_zone("Edinburgh")
edinburgh_1km = edinburgh |>
  # Change number in next line to change zone size:
  filter(circle_id <= 1)
osm = get_travel_network("Scotland")
cycle_network = get_cycling_network(osm)
driving_network = get_driving_network(osm)
edinburgh_cycle = cycle_network[edinburgh_1km, , op = sf::st_within]
edinburgh_driving = driving_network[edinburgh_1km, , op = sf::st_within]
edinburgh_cycle_with_distance = distance_to_road(edinburgh_cycle, edinburgh_driving)
edinburgh_segregated = classify_cycleways(edinburgh_cycle_with_distance)
table(edinburgh_segregated$cycle_segregation)
m = edinburgh_segregated |>
  arrange(cycle_segregation) |>
  tm_shape() + tm_lines("cycle_segregation", lwd = 4, palette = "-Blues", popup.vars = c("name", "cycle_segregation", "distance_to_road", "maxspeed", "highway", "other_tags"))
m
# tmap_save(m, "classify_cycleways_edinburgh.html")
```

Save an interactive version of the map to check the results as follows:

```{r}
#| eval: false
tmap_save(m, "classify_cycleways_edinburgh.html")
browseURL("classify_cycleways_edinburgh.html")
```

## Lisbon example

```{r lisbon}
#| eval: false
lisbon = zonebuilder::zb_zone("Lisbon")
lisbon = sf::st_sf(
  lisbon |> sf::st_drop_geometry() |> select(-centroid),
  geometry = sf::st_geometry(lisbon)
)
lisbon = lisbon |>
  filter(circle_id == 1)
u = "https://github.com/U-Shift/SiteSelection/releases/download/0.1/CAOP_municipios.gpkg"
f = basename(f)
if (!file.exists(f)) download.file(u, f)
PTcities = sf::read_sf(f) # Portugal
lisbon = PTcities |> filter(Concelho == "Lisboa")
lisbon = lisbon |>
  sf::st_convex_hull()
f = list.files("~/data/osm", pattern = "portugal*.+pbf", full.names = TRUE)
osm = sf::read_sf(f, query = "select * from lines where highway is not null")
osm = get_travel_network("Portugal", boundary = lisbon, boundary_type = "clipsrc", force_vectortranslate = TRUE)
list.files("~/data/osm", pattern = "portugal")
cycle_network = get_cycling_network(osm)
driving_network = get_driving_network(osm)
cycle_network_with_distance = distance_to_road(cycle_network, driving_network)
lisbon_categorized = classify_cycleways(cycle_network_with_distance)
m = lisbon_categorized |>
  arrange(cycle_segregation) |>
  tm_shape() + tm_lines("cycle_segregation", lwd = 4, palette = "-Blues", popup.vars = c("name", "cycle_segregation", "distance_to_road", "maxspeed", "highway", "other_tags"))
m
```

```{r}
#| eval: false
tmap_save(m, "classify_cycleways_lisbon.html")
browseURL("classify_cycleways_lisbon.html")
```