name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/geocompx/latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install osmactive package
      run: R -e 'remotes::install_local(".")'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-and-push-action@v6
      with:
        context: .
        push: true
        tags: ghcr.io/nptscot/osmactive:latest
